// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lorenzhoerb/cogniprice/services/scheduler/internal/scheduler (interfaces: JobRepository)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_scheduler_job_repository.go -mock_names=JobRepository=MockSchedulerJobRepository -package=mocks . JobRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/lorenzhoerb/cogniprice/services/scheduler/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSchedulerJobRepository is a mock of JobRepository interface.
type MockSchedulerJobRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerJobRepositoryMockRecorder
	isgomock struct{}
}

// MockSchedulerJobRepositoryMockRecorder is the mock recorder for MockSchedulerJobRepository.
type MockSchedulerJobRepositoryMockRecorder struct {
	mock *MockSchedulerJobRepository
}

// NewMockSchedulerJobRepository creates a new mock instance.
func NewMockSchedulerJobRepository(ctrl *gomock.Controller) *MockSchedulerJobRepository {
	mock := &MockSchedulerJobRepository{ctrl: ctrl}
	mock.recorder = &MockSchedulerJobRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSchedulerJobRepository) EXPECT() *MockSchedulerJobRepositoryMockRecorder {
	return m.recorder
}

// GetDue mocks base method.
func (m *MockSchedulerJobRepository) GetDue(limit int) ([]*model.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDue", limit)
	ret0, _ := ret[0].([]*model.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDue indicates an expected call of GetDue.
func (mr *MockSchedulerJobRepositoryMockRecorder) GetDue(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDue", reflect.TypeOf((*MockSchedulerJobRepository)(nil).GetDue), limit)
}

// SaveAll mocks base method.
func (m *MockSchedulerJobRepository) SaveAll(job []*model.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveAll", job)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveAll indicates an expected call of SaveAll.
func (mr *MockSchedulerJobRepositoryMockRecorder) SaveAll(job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveAll", reflect.TypeOf((*MockSchedulerJobRepository)(nil).SaveAll), job)
}
