// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lorenzhoerb/cogniprice/services/scheduler/internal/scheduler (interfaces: Dispatcher)
//
// Generated by this command:
//
//	mockgen -destination=../../mocks/mock_dispatcher.go -package=mocks . Dispatcher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/lorenzhoerb/cogniprice/services/scheduler/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDispatcher is a mock of Dispatcher interface.
type MockDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockDispatcherMockRecorder
	isgomock struct{}
}

// MockDispatcherMockRecorder is the mock recorder for MockDispatcher.
type MockDispatcherMockRecorder struct {
	mock *MockDispatcher
}

// NewMockDispatcher creates a new mock instance.
func NewMockDispatcher(ctrl *gomock.Controller) *MockDispatcher {
	mock := &MockDispatcher{ctrl: ctrl}
	mock.recorder = &MockDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispatcher) EXPECT() *MockDispatcherMockRecorder {
	return m.recorder
}

// DispatchJobs mocks base method.
func (m *MockDispatcher) DispatchJobs(jobs []model.JobDispatched) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DispatchJobs", jobs)
	ret0, _ := ret[0].(error)
	return ret0
}

// DispatchJobs indicates an expected call of DispatchJobs.
func (mr *MockDispatcherMockRecorder) DispatchJobs(jobs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatchJobs", reflect.TypeOf((*MockDispatcher)(nil).DispatchJobs), jobs)
}
