// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lorenzhoerb/cogniprice/services/scheduler/internal/api/http (interfaces: JobService)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/lorenzhoerb/cogniprice/services/scheduler/internal/model"
)

// MockJobService is a mock of JobService interface.
type MockJobService struct {
	ctrl     *gomock.Controller
	recorder *MockJobServiceMockRecorder
}

// MockJobServiceMockRecorder is the mock recorder for MockJobService.
type MockJobServiceMockRecorder struct {
	mock *MockJobService
}

// NewMockJobService creates a new mock instance.
func NewMockJobService(ctrl *gomock.Controller) *MockJobService {
	mock := &MockJobService{ctrl: ctrl}
	mock.recorder = &MockJobServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobService) EXPECT() *MockJobServiceMockRecorder {
	return m.recorder
}

// CreateJob mocks base method.
func (m *MockJobService) CreateJob(arg0 *model.CreateJobRequest) (*model.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateJob", arg0)
	ret0, _ := ret[0].(*model.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateJob indicates an expected call of CreateJob.
func (mr *MockJobServiceMockRecorder) CreateJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateJob", reflect.TypeOf((*MockJobService)(nil).CreateJob), arg0)
}

// DeleteJob mocks base method.
func (m *MockJobService) DeleteJob(arg0 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockJobServiceMockRecorder) DeleteJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockJobService)(nil).DeleteJob), arg0)
}

// GetJobByID mocks base method.
func (m *MockJobService) GetJobByID(arg0 int) (*model.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetJobByID", arg0)
	ret0, _ := ret[0].(*model.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetJobByID indicates an expected call of GetJobByID.
func (mr *MockJobServiceMockRecorder) GetJobByID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetJobByID", reflect.TypeOf((*MockJobService)(nil).GetJobByID), arg0)
}

// ListJobs mocks base method.
func (m *MockJobService) ListJobs(arg0 *model.ListJobsFilter) (*model.PaginatedJobsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListJobs", arg0)
	ret0, _ := ret[0].(*model.PaginatedJobsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListJobs indicates an expected call of ListJobs.
func (mr *MockJobServiceMockRecorder) ListJobs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListJobs", reflect.TypeOf((*MockJobService)(nil).ListJobs), arg0)
}

// PauseJob mocks base method.
func (m *MockJobService) PauseJob(arg0 int) (*model.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseJob", arg0)
	ret0, _ := ret[0].(*model.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PauseJob indicates an expected call of PauseJob.
func (mr *MockJobServiceMockRecorder) PauseJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseJob", reflect.TypeOf((*MockJobService)(nil).PauseJob), arg0)
}

// ResumeJob mocks base method.
func (m *MockJobService) ResumeJob(arg0 int) (*model.JobResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeJob", arg0)
	ret0, _ := ret[0].(*model.JobResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResumeJob indicates an expected call of ResumeJob.
func (mr *MockJobServiceMockRecorder) ResumeJob(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeJob", reflect.TypeOf((*MockJobService)(nil).ResumeJob), arg0)
}
